name: CD to Render

on:
  push:
    branches:
      - main  # Trigger only on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          echo "Triggering Render deployment..."
          curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"
