name: CD to Render

on:
  workflow_run:
    workflows: ["docker-build-push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          echo "✅ CI workflow completed successfully. Triggering Render deployment..."
          curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"

